# {{crate}}

<!-- This file was @generated by cargo-readme -->

<p>
<a href="https://docs.rs/{{crate}}/"><img src="https://docs.rs/{{crate}}/badge.svg" alt="docs.rs"></a> <a href="https://crates.io/crates/{{crate}}"><img src="https://img.shields.io/crates/v/{{crate}}"></a> <img src="https://img.shields.io/badge/license-MIT%2FApache--2.0-blue">
</p>

{{readme}}

## License

{{license}}